name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-easyctl-linux-amd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build linux-adm64
      env:
        CGO_ENABLED: 0
        GOARCH: amd64
        GOOS: linux
      run: go build -o easyctl && tar zcvf easyctl-linux-adm64.tgz easyctl
    - name: Create Release # 创建Release，可以在仓库看到一个个版本
      env:
        GITHUB_TOKEN: ${{ secrets.EASYCTL_PUBLISH_TOKEN }}
      id: create_release
      uses: actions/create-release@master
      with:
        tag_name: ${{ github.ref }} # (tag)标签名称
        release_name: Release ${{ github.ref }}
        draft: false # 是否是草稿
        prerelease: false # 是否是预发布
    - name: Upload Release Asset
      id: upload-release-asset-linux-amd64
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.EASYCTL_PUBLISH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传地址，通过创建Release获取到的
        asset_path: ./easyctl-linux-adm64.tgz # 要上传文件
        asset_name: easyctl-linux-adm64.tgz # 上传后的文件名
        asset_content_type: application/x-tgz

#  build-easyctl-macos:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.16
#      - name: Build darwin
#        env:
#          CGO_ENABLED: 0
#          GOARCH: darwin
#          GOOS: linux
#        run: go build -o easyctl && tar zcvf easyctl-darwin-adm64.tgz easyctl
#      - name: Create Release # 创建Release，可以在仓库看到一个个版本
#        env:
#          GITHUB_TOKEN: ${{ secrets.EASYCTL_PUBLISH_TOKEN }}
#        id: create_release
#        uses: actions/create-release@master
#        with:
#          tag_name: ${{ github.ref }} # (tag)标签名称
#          release_name: Release ${{ github.ref }}
#          draft: false # 是否是草稿
#          prerelease: false # 是否是预发布
#      - name: Upload Release Asset
#        id: upload-release-asset-darwin-adm64
#        uses: actions/upload-release-asset@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.EASYCTL_PUBLISH_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传地址，通过创建Release获取到的
#          asset_path: ./easyctl-darwin-adm64.tgz # 要上传文件
#          asset_name: easyctl-darwin-adm64.tgz # 上传后的文件名
#          asset_content_type: application/x-tgz

  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.18.2
      - name: install gitbook
        run: npm install gitbook-cli gitbook-summary -g
        working-directory: book
      - name: set timezone
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: install
        run: gitbook install
        working-directory: book
      - name: generate-toc
        run: book sm --disableTitleFormatting
        working-directory: book
      - name: build
        run: gitbook build
        working-directory: book
      - name: install git
        run: sudo apt-get install git -y
      - name: publish
        env:
          ACCESS_TOKEN: ${{ secrets.EASYCTL_PUBLISH_TOKEN }}
        run: |
          mkdir -p deploy-doc-dir
          cd deploy-doc-dir
          rm -rf *
          git init
          git config user.name "weiliang-ms"
          git config user.email "xzx.weiliang@gmail.com"
          ls -R ../book/_book
          mv ../book/_book docs
          git add docs
          git commit -m "Update docs"
          git push --force "https://$ACCESS_TOKEN@github.com/weiliang-ms/easyctl" master:docs
