name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-easyctl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v ./...

  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.18.2
      - name: install gitbook
        run: npm install gitbook-cli gitbook-summary -g
      - name: install
        run: gitbook install
      - name: generate-toc
        run: book sm --disableTitleFormatting book
      - name: build
        run: node -v && gitbook build book
      - name: index
        run: ls
      - name: install git
        run: sudo apt-get install git -y
      - name: publish
        run: |
          mkdir -p deploy-doc-dir
          cd deploy-doc-dir
          echo ${{ secrets.publish }}
#          git init
#          git config user.name "weiliang-ms"
#          git config user.email "xzx.weiliang@gmail.com"
#          mv ../book/_book docs
#          git add docs
#          git commit -m "Update docs"
#          git push --force "https://$GH_TOKEN@$GH_REF" master:docs

        #    - name: Test
#      run: go test -v ./...
